// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kaxqvfgmvfebnskwayit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtheHF2ZmdtdmZlYm5za3dheWl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0NzEwNzUsImV4cCI6MjA1NDA0NzA3NX0.15th4U9knMgIJc70TtF1ENZ0RLBZqQ5yvmB66JCEB3Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);